# Generated by Django 5.2.4 on 2025-07-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='library',
            field=models.ManyToManyField(blank=True, help_text="Assets added to the user's library.", related_name='in_libraries', to='assets.asset'),
        ),
    ]
