# Generated by Django 5.0.4 on 2025-08-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_userprofile_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark this asset as featured.'),
        ),
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Price in USD. Leave 0 for free assets.', max_digits=10, null=True),
        ),
    ]
