# Generated by Django 5.2.4 on 2025-08-05 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_is_featured_asset_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category', 'is_featured'], name='assets_asse_categor_6bc142_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['creator', 'created_at'], name='assets_asse_creator_39c98d_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['is_featured', 'created_at'], name='assets_asse_is_feat_060bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['price'], name='assets_asse_price_fa3e74_idx'),
        ),
    ]
